# Generated by Django 4.2 on 2025-05-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(db_column='ID_Materia', primary_key=True, serialize=False)),
                ('nombre_materia', models.CharField(blank=True, db_column='Nombre_Materia', max_length=100, null=True)),
            ],
            options={
                'db_table': 'materia',
            },
        ),
    ]
