# Generated by Django 4.2 on 2025-05-20 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(db_column='ID_Actividad', primary_key=True, serialize=False)),
                ('nota', models.CharField(blank=True, db_column='Nota', max_length=1, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('clase', models.ForeignKey(db_column='ID_Clase', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clases.clase')),
            ],
            options={
                'db_table': 'actividad',
            },
        ),
    ]
