# Generated by Django 4.2 on 2025-05-20 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0002_estudiante_delete_persona'),
        ('cursos', '0001_initial'),
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clase', models.AutoField(db_column='ID_Clase', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('asistencia', models.CharField(blank=True, db_column='Asistencia', max_length=10, null=True)),
                ('curso', models.ForeignKey(db_column='ID_Curso', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.curso')),
                ('estudiante', models.ForeignKey(db_column='ID_Estudiante', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.estudiante')),
                ('materia', models.ForeignKey(db_column='ID_Materia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='materias.materia')),
            ],
            options={
                'db_table': 'clase',
            },
        ),
    ]
