# Generated by Django 4.2 on 2025-06-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='clase',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
