# Generated by Django 4.2 on 2025-05-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(db_column='ID_Curso', primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(db_column='Nombre_Curso', max_length=100)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
            ],
            options={
                'db_table': 'curso',
            },
        ),
    ]
