# Generated by Django 4.2 on 2025-06-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('Nombre_Usuario', models.CharField(max_length=50, unique=True)),
                ('Contrasena', models.CharField(max_length=200)),
                ('Rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Director', 'Director'), ('Profesor', 'Profesor'), ('Personal_Administrativo', 'Personal Administrativo'), ('Acudiente', 'Acudiente')], max_length=30)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
