# Generated by Django 4.2 on 2025-06-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Profesor', 'Profesor')], max_length=30),
        ),
    ]
