# Generated by Django 4.2 on 2025-05-20 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(db_column='ID_Estudiante', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='Apellido', max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, db_column='Fecha_Nacimiento', null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=15, null=True)),
                ('correo_electronico', models.EmailField(blank=True, db_column='Correo_Electronico', max_length=100, null=True)),
                ('nivel_academico', models.CharField(blank=True, db_column='Nivel_Academico', max_length=50, null=True)),
                ('curso', models.ForeignKey(db_column='ID_Curso', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='cursos.curso')),
            ],
            options={
                'db_table': 'estudiante',
            },
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
