# Generated by Django 4.2 on 2025-05-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(db_column='ID_Persona', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='Apellido', max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, db_column='Fecha_Nacimiento', null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=15, null=True)),
                ('correo_electronico', models.EmailField(blank=True, db_column='Correo_Electronico', max_length=100, null=True)),
                ('rol', models.CharField(choices=[('Acudiente', 'Acudiente'), ('Profesor', 'Profesor'), ('Administrador', 'Administrador')], db_column='Rol', max_length=20)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
    ]
